services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
      - ./data:/data
    ports:
      - "21465:21465"
volumes:
  wppconnect_tokens: {}


